### ISSUE TITLE
vacuum devices are deprecated in HA

### ISSUE THREAD

**Issue by jarkastr** [opravdin/weback-hass#1]
It appears, that the only way to set up a vacuum in HA is as a Vacuum entity.  integration should be updated to account for deprecation.

**Comment by jarkastr** [comment]
This is actually much easier to fix than i anticipated.  Just change all instances of VacuumDevice to VacuumEntity.

**Comment by dvb76** [comment]
Hi Jarkastr, how did you do it?
I'm a noob and did not see literally the Vacuum device, sometimes see device and other times devices, should all be replaced with entity and entities?
Or will the repository be updated so the new version comes via HACS?
Br. DvB

**Comment by jarkastr** [comment]
Load via HACS,  then navigate to the folder that it is installed into.  Go
through the code files (maybe only 3) and change all instances of
VacuumDevice to VacuumEntity.  I don't know how to commit code in github,
otherwise I would have and it would work without having to go into the HACS
repository on your machine.

**Comment by opravdin** [comment]
Fixed that in last version :)
