### ISSUE TITLE
ziglint d5 vacuum not appear in home assistant entities

### ISSUE THREAD

**Issue by bubidj** [opravdin/weback-hass#11]
work well up to version 1.0.1, then I have not seen the entity anymore..

(sorry for my bad english)

**Comment by bubidj** [comment]
I found this 2 messages in register:

- weback: Error on device update!
- VacuumDevice is deprecated, modify WebackVacuum to extend VacuumEntity

**Comment by bubidj** [comment]
I found a solution.

1) install 1.0.0 version from hacs
2) restart HA
3) add account in configuration.yaml
4) restart HA
5) if all ok you found vacuum entity in HA
6) upgrade to the last version of the integration and restart again.

work for me

**Comment by opravdin** [comment]
> I found this 2 messages in register:
> 
> * weback: Error on device update!
> * VacuumDevice is deprecated, modify WebackVacuum to extend VacuumEntity

It looks like you have using old version of integration. Update on last version fixed it

**Comment by JR-aaas** [comment]
Integration still doesn't work.
The Weback version 1.0.0 entity loads, it is not possible to work with it.
Weback version 1.0.3  -  HA displays an Invalid config error

configuration.yaml
weback:
     username: + 420-111111111
     password: ********
