### ISSUE TITLE
Integration still doesn't work  Vacuum cleaner Concept

### ISSUE THREAD

**Issue by JR-aaas** [opravdin/weback-hass#12]
Integration still doesn't work.
The Weback version 1.0.0 entity loads, it is not possible to work with it.
Weback version 1.0.3 - HA displays an Invalid config error

configuration.yaml
weback:
username: + 420-111111111
password: ********

And logs:

Setup failed for weback: No setup function defined.
11:52:25 AM – setup.py (ERROR)

**Comment by opravdin** [comment]
1) you have space between plus and 420, remove it
2) versions lower than 1.0.3 are not working ones because of revoked Amazon certificate on the endpoint used there
3) try to reinstall latest version

**Comment by opravdin** [comment]
Also some users have issues with passwords containing some special characters

**Comment by JR-aaas** [comment]
oh sorry  the number is    +420-777000000
The password is one uppercase letter and 6 lowercase letters   ( Aaaaaaa)

**Comment by JR-aaas** [comment]
![inv config](https://user-images.githubusercontent.com/62484901/108227922-aa0fb800-713e-11eb-92b1-ea12d4ae1e31.png)
![ver](https://user-images.githubusercontent.com/62484901/108227939-ae3bd580-713e-11eb-8302-ffaa2be49691.png)
![2021_02_17_16_36_59_Window](https://user-images.githubusercontent.com/62484901/108227959-b3008980-713e-11eb-8a17-082d700e4651.png)

**Comment by opravdin** [comment]
What's in logs?

**Comment by JR-aaas** [comment]
I'm collecting a log now

**Comment by JR-aaas** [comment]
Ooo unbelievable - the problem was in another entity ... The foreign entity affected the python ... I deleted the Raspberry uptime integration and everything works

**Comment by opravdin** [comment]
> Ooo unbelievable - the problem was in another entity ... The foreign entity affected the python ... I deleted the Raspberry uptime integration and everything works

Nice to hear that. I am closing the issue since it's working now

**Comment by JR-aaas** [comment]
OK
