### ISSUE TITLE
Invalid config | The following integrations and platforms could not be set up:  weback

### ISSUE THREAD

**Issue by rdnsx** [opravdin/weback-hass#2]
Hi, 

i installed weback cloud intergration from HACS. I entered the following into the configuration.yaml:

```
weback:
    username: +49-1234567890
    password: *********
```

After restarting HA it gives me "Invalid config | The following integrations and platforms could not be set up:  weback | Please check your config".

Ideas of whats wrong?

Home Assistant 0.113.0
HACS 1.2.2
Weback cloud integration v1.0
Vacuum: Tesvor X500

**Comment by NinDTendo** [comment]
if your number is 0171234567 in germany
username should be : +49-0171234567

**Comment by forkfavicon** [comment]
> 
> 
> if your number is 0171234567 in germany
> username should be : +49-0171234567

Hi. I have the same problem. Region +7. I try to write +7-1111111111, +7-71111111111, +7-81111111111. Still the same mistake

**Comment by NinDTendo** [comment]
in your `config.yaml` it should look like this

```
weback:
    username: +7-0123456789
    password: [your password]
```

if your country code is +7(when registering account you have to select the country above the email/phone number)
and phone number with the 0 

atleast for me it solved this exact problem you are having.

**Comment by JR-aaas** [comment]
I have the same problem.

My area code is +420 and number is 123456789.
Saving +420-123456789, +42-0123456789 and various combinations, still configuration error.
I entered the e-mail address ****@****.com still the same problem.

You know where the mistake is?

**Comment by forkvidikon** [comment]
Hello everyone. For those who are faced with a similar problem, I recommend changing the password to a less persistent one. No special characters. In my case, it worked

**Comment by opravdin** [comment]
Maybe you should try to quote your password in config. Could you provide me example of password string? (you could shuffle characters or add/change some english letters and digits)

**Comment by opravdin** [comment]
Since no steps to reproduce the error are presented, I will close this question for now.

**Comment by Juanko984** [comment]
I am also not able to configure this integration, getting the below error:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:663
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:42:28 AM (1 occurrences)
Last logged: 10:42:28 AM

The system cannot restart because the configuration is not valid: Integration error: weback - Integration 'weback' not found.
