### ISSUE TITLE
Requirements not found

### ISSUE THREAD

**Issue by PRabahy** [opravdin/weback-hass#4]
I just installed this via HACS and am getting the following error:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:365
Integration: Hass.io (documentation, issues)
First occurred: 3:35:22 PM (1 occurrences)
Last logged: 3:35:22 PM
Component error: weback - Requirements for weback not found: ['weback-unofficial==0.3.4']. 

I'm using home assistant on a raspberry pi using hassio (I think now called Home Assistant Operating System =) if that matters.

**Comment by opravdin** [comment]
I am in process of upgrading (and restoring my hass from broken SD card) for now. Will be fixed soon

**Comment by opravdin** [comment]
It should work now

**Comment by PRabahy** [comment]
Confirmed! I now have my vacuum working in Home Assistant! Thanks for all your work integrating this!
