### ISSUE TITLE
Webcak : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

### ISSUE THREAD

**Issue by ramrajg** [opravdin/weback-hass#8]
Hi 
I am getting following error 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
in home assistants

**Comment by opravdin** [comment]
Duplicate of #6
