### ISSUE TITLE
[request] new device: tendomi air purifier

### ISSUE THREAD

**Issue by zandadoum** [opravdin/weback-hass#9]
Hello,

I have an air purifier from TENDOMI that is managed through the weback mobile app and i was hoping there could be support added so i can control it from home assistant

this is the device:
https://www.amazon.com/TENDOMI-Air-Purifier-Purifiers-Allergies/dp/B07YB1DHRK

with the app i can control:
- on/off
- rotate on/off
- led on/off and colors
- fan speeds
- a % sensor that tells the usage of the filter
- a timer function to turn it on/off

i would be very happy if some of those things could be implemented :D

**Comment by opravdin** [comment]
Sorry, can't implement that because I don't have access to this type of weback devices. You can make some researches with my weback-unofficial class and find all nescessary parameters you need to implement support of this type of devices.
